alias l='ls -alhF'
alias grep='grep --color=auto'
alias ..='cd ..'
alias c='clear'
alias t='touch'
alias md='mkdir -p'
alias ping='ping -c 3 https://archlinux.org'
alias vi='neovim'
alias gc='git clone'
